#include "./sgemm_header_file/kernel0.cuh"
#include "./sgemm_header_file/kernel1.cuh"
#include "./sgemm_header_file/kernel2.cuh"
#include "./sgemm_header_file/kernel3.cuh"
#include "./sgemm_header_file/kernel4.cuh"
#include "./sgemm_header_file/kernel5.cuh"
#include "./sgemm_header_file/kernel6.cuh"
#include "./sgemm_header_file/kernel7.cuh"
#include "./sgemm_header_file/kernel8.cuh"
#include "./sgemm_header_file/kernel9.cuh"
// #include "./kernel11.cuh"